# SPDX-FileCopyrightText: 2026 Wiktor Bryk <contact@itsvic.dev>
#
# SPDX-License-Identifier: GPL-3.0-or-later

sonar.projectKey=softmodem-rs
sonar.projectName=softmodem
sonar.sources=.
sonar.exclusions=target/**,nix/Cargo.nix
sonar.rust.clippy.reportPaths=clippy.json
sonar.rust.lcov.reportPaths=lcov.info
