# SPDX-FileCopyrightText: 2026 Wiktor Bryk <contact@itsvic.dev>
#
# SPDX-License-Identifier: GPL-3.0-or-later

sonar.projectKey=itsvic-dev_softmodem-rs_726daf1c-48d5-45a7-ae0b-2e2bddbfc1a5
sonar.projectName=softmodem
sonar.sources=.
sonar.exclusions=target/**,nix/Cargo.nix
# CI builds and tests only the Rust workspace.
sonar.coverage.exclusions=android/**
sonar.qualitygate.wait=true
sonar.rust.clippy.enabled=false
sonar.rust.clippy.reportPaths=clippy.json
sonar.rust.lcov.reportPaths=lcov.info
