# SPDX-FileCopyrightText: 2026 Wiktor Bryk <contact@itsvic.dev>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "softmodem-slmodem"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "slmodem-bridge"
path = "src/main.rs"

[dependencies]
softmodem-transport.workspace = true

anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
