# SPDX-FileCopyrightText: 2026 Wiktor Bryk <contact@itsvic.dev>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "softmodem-terminal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rustix.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
