[package]
name = "softmodem-transport"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
ezk-rtp.workspace = true
fastrand.workspace = true
hound.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
